### ISSUE TITLE
How to omit this function advance() when decoding.

### ISSUE THREAD

**Issue by Jamaika1** [osamu620/OpenHTJ2K#100]
I know the codec is under development. I have a query for the advance() function.
https://github.com/osamu620/OpenHTJ2K/commit/f3af95b5ea913311cb52cfdb33e9ae6aac9c9085
How to omit this function when decoding.
htj2k-cjhc.exe -i image_21447_24bit.ppm -o image_21447_24bit-jhc.j2c Creversible=yes -num_threads 1
elapsed time for reading inputs 24.939         [ms]
585.866474 [MB/s]
Codestream bytes  = 3703013 = 12.165187 [bits/pixel]
elapsed time 297.912        [ms]
htj2k-djhc.exe -i image_21447_24bit-jhc.j2c -o image_21447_24bit-jhc_hc.ppm -num_threads 1
ERROR: n = -1, n
Did I forget to add some function from help?

**Comment by osamu620** [comment]
@Jamaika1 
The code in the development branch has only been tested with clang on macOS, Linux, and MSVC 2022 compiler. Which compiler do you use?

**Comment by Jamaika1** [comment]
I assume gcc has no bugs.
I am using gcc 11.3.1 and 13.0.0 64bit

**Comment by Jamaika1** [comment]
Hmm... It doesn't work for me in C++17 win10. Thanks for your willingness
https://www.sendspace.com/file/l6mr8c

**Comment by osamu620** [comment]
@Jamaika1 
Just a quick confirmation. You are using GCC 11.3.1 in MinGW (or msys2) environment?

**Comment by Jamaika1** [comment]
Only
http://msystem.waw.pl/x265/mingw-gcc1131-20220429.7z
sometimes for comparison
http://www.equation.com/servlet/equation.cmd?fa=fortran

**Comment by Jamaika1** [comment]
Only
http://msystem.waw.pl/x265/mingw-gcc1131-20220429.7z
sometimes for comparison 13.0.0
http://www.equation.com/servlet/equation.cmd?fa=fortran
plus
https://github.com/Jamaika1/mingw_std_threads

Codec has recently started responding.
```
ERROR: illegal attempt to advance 35 bits but there are 34 bits left in MagSgn advance
ERROR: illegal attempt to advance 35 bits but there are 32 bits left in MagSgn advance
ERROR: illegal attempt to advance 35 bits but there are 32 bits left in MagSgn advance
ERROR: illegal attempt to advance 34 bits but there are 33 bits left in MagSgn advance
ERROR: illegal attempt to advance 33 bits but there are 32 bits left in MagSgn advance
ERROR: illegal attempt to advance 33 bits but there are 32 bits left in MagSgn advance
ERROR: illegal attempt to advance 34 bits but there are 32 bits left in MagSgn advance
ERROR: illegal attempt to advance 33 bits but there are 32 bits left in MagSgn advance
ERROR: illegal attempt to advance 33 bits but there are 32 bits left in MagSgn advance
ERROR: illegal attempt to advance 33 bits but there are 32 bits left in MagSgn advance
ERROR: illegal attempt to advance 33 bits but there are 32 bits left in MagSgn advance
elapsed time 249.210        [ms]
throughput 29.314482 [Msamples/s]
throughput 0.034113 [usec/sample]
```

My codecs today. 
https://www.sendspace.com/file/fym2ru

**Comment by osamu620** [comment]
Are you sure that you used the latest main branch as is?

**Comment by Jamaika1** [comment]
I don't think that I was wrong. You can create codec yourself.
Opensource: https://www.sendspace.com/file/msnea1
https://github.com/osamu620/OpenHTJ2K/commit/c75bb70be3d56772511f13b91b5e4b7d0df57176#diff-a4a8fb73e3cec05ace52ef98e3e0e8f6f7d4d59b1271a15696322089be09ae93

**Comment by osamu620** [comment]
I couldn't reproduce the problem. That's why I asked the above question.

What is the”create codec”?

**Comment by Jamaika1** [comment]
Today I have heat in Poland. I will spend some time testing gcc 11.3.1.
Please do not laugh at the inquiries of an amateur. I know that errors can be found in 5 minutes using specialized programs.
https://github.com/osamu620/OpenHTJ2K/commit/90a059ab84f9ba13c0eb0a09ada9de5b5828cbdf
Codec works.

**Comment by osamu620** [comment]
@Jamaika1 
Thanks for the results of the testing. I have also found that this line
https://github.com/osamu620/OpenHTJ2K/blob/2ce63d2fa5a3f884c382f0501be124ba98ecb16a/source/core/coding/ht_block_decoding.hpp#L441
does not work correctly with GCC (9.4, 10.x, 11.x).

Do you have any thoughts on this?

**Comment by Jamaika1** [comment]
https://stackoverflow.com/questions/12261915/how-to-throw-stdexceptions-with-variable-messages
For C++20 `#include <format>`
`#if defined(__clang__)
throw std::runtime_error(std::format("ERROR: illegal attempt to advance {:15d} bits but there are {:15d} bits left in MagSgn advance", n, bits));
#endif`
GCC doesn't have `std::format`.

**Comment by ValZapod** [comment]
> does not work correctly with GCC (9.4, 10.x, 11.x).

LOL

**Comment by osamu620** [comment]
> > does not work correctly with GCC (9.4, 10.x, 11.x).
> 
> LOL

I have no idea why this line is problematic with only such compilers..
