### ISSUE TITLE
Problem with decoding

### ISSUE THREAD

**Issue by Jamaika1** [osamu620/OpenHTJ2K#124]
OpenHTJ2K ver. https://github.com/osamu620/OpenHTJ2K/commit/7e59ff1535324484aaae10197168f99b6387d629
https://ibb.co/wpfj7Zg

**Comment by osamu620** [comment]
I can see the attached images, however, the detailed information on; compilers, OS, encoding parameters, etc. should be provided from you.

**Comment by Jamaika1** [comment]
GCC 11.3.1 20220429 no SIMD

**Comment by osamu620** [comment]
How old is your computer? AVX2 is supported on Haswell or newer generations.

**Comment by Jamaika1** [comment]
I don't know about SIMD compression in GCC.
I compiled for `x86-64` processors in gcc. I donn't use the `march=haswell` option.

My computer.
I do not know about SIMD compression

[Microsoft Windows 10 Pro]
[10.0.19043 Kompilacja 19043]
[Procesor]
[Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz, 3301 MHz, Rdzenie: 4, Procesory logiczne: 4]
[Wersja/data systemu BIOS]
[Intel Corp. BAP6710H.86A.0079.2012.0622.1722, 22.06.2012]

**Comment by osamu620** [comment]
@Jamaika1 
Thanks. The i5-2500K supports up to AVX, so AVX2 is not supported.

If possible, could you provide the codestream (.j2c) and commit-hash of the compiled .exe? I could not open .rar file.

**Comment by Jamaika1** [comment]
It's better. The codec only supports standard photo sizes, e.g. 1280x720.
There is still a problem for 4000x3000.

I lack information in the SIMD codecs. Eg Error - Your CPU is not supported. I don't even know if the codec should show help for AVX2.
https://www.sendspace.com/filegroup/KO5NUl0y3HpE%2Bs54JIsldFcGQqP2RzzBNiqciGySVT0
