### ISSUE TITLE
Why can I not use capital letters in photo names?

### ISSUE THREAD

**Issue by Jamaika1** [osamu620/OpenHTJ2K#125]
htj2k-cjhc.exe -i Stationery.ppm -o image_21447_24bit-jhc.j2c Stiles={1000,750} Clevels=3 Cblk={64,64} Cprecincts={128,128},{256,256} Corder=CPRL Creversible=yes
```
ERROR: unknown parameter Stationery.ppm
```

**Comment by osamu620** [comment]
I think the decoder app has a bug. I have little time to hunt it down.

**Comment by osamu620** [comment]
@Jamaika1 
Thanks for pointing this issue out. I've checked the code and found that files that begin from capital 'S' or 'C' are not recognized as names for the inputs. This problem comes from my silly command-line parser. I'll fix this problem when I have time.

**Comment by Jamaika1** [comment]
Test https://github.com/osamu620/OpenHTJ2K/commit/e0417dd41a8cf5721f0af649bcf7bef30c2aa861 NOSIMD
There is still an error despite adding the parentheses.
ERROR: unknown parameter Stationery.ppm

**Comment by osamu620** [comment]
> Test [e0417dd](https://github.com/osamu620/OpenHTJ2K/commit/e0417dd41a8cf5721f0af649bcf7bef30c2aa861) NOSIMD There is still an error despite adding the parentheses. ERROR: unknown parameter Stationery.ppm

Could you please check this again with the latest main branch? (I have fixed a potential bug, but I think it is not related to this problem...
