### ISSUE TITLE
Add installation to CMake

### ISSUE THREAD

**Issue by jubalh** [osamu620/OpenHTJ2K#154]
I see the installation part is still commented out:
https://github.com/osamu620/OpenHTJ2K/blob/main/CMakeLists.txt#L169
The README also so far mentions just the build process and no install. So I assume this is intentionally not ready yet :)

I just wanted to open this issue to keep track of this that I can get notified when it's ready.

I started to create a test package for openSUSE in my [home repo](https://build.opensuse.org/package/show/home:jubalh/openhtj2k). Just to experiment with it and later once everything is ready push it to the main distribution.

**Comment by osamu620** [comment]
Hi @jubalh , thanks for raising this issue.
Because I'm unfamiliar with packaging stuff with CMake, yes, it has been intentionally commented out.

Your suggestion and/or knowledge are more than welcome :)

**Comment by jubalh** [comment]
I will set put it on my TODO to check this :) Don't know quite yet when I will find the time.

**Comment by osamu620** [comment]
FYI - I have filled the installation part (fe70b1b1879e59eac499ca323e07bd732245b65e).

**Comment by jubalh** [comment]
Great! Thanks!
I updated the package and it builds and install fine.
I noticed that the `imgcmp` binary isn't installed. Is this intentional?

**Comment by osamu620** [comment]
@jubalh 
Yes, `imgcmp` is just a tool for conformance testing. I think tools like `compare` in ImageMagick are much more universal. Make sense?

**Comment by jubalh** [comment]
Perfect :)
