### ISSUE TITLE
Support for armv7-a architecture

### ISSUE THREAD

**Issue by v2aus** [osamu620/OpenHTJ2K#158]
Hello.
It seems that OpenHTJ2K now doesn't support armv7-a. I tried to modify the CmakeLists.txt to cross-compile the source code with GCC 6.3.0. Finally, I failed.
I set CMAKE_CXX_STANDARD to 14 and CMAKE_HOST_SYSTEM_PROCESSOR to arm32, and then I added some code about CMAKE_HOST_SYSTEM_PROCESSOR matching arm32 to CmakeLists.txt. I set ENABLE_ARM_NEON to "OFF" because there is no definition of vaddv_u8().
I set -march=armv7-a -mtune=cortex-7a. At last, the compilation went to the following step:

> [ 93%] Linking CXX executable bin/open_htj2k_enc
bin/libopen_htj2k_R.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_notify_all(unsigned int*)'
bin/libopen_htj2k_R.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/open_htj2k_enc.dir/build.make:85: bin/open_htj2k_enc] Error 1
make[1]: *** [CMakeFiles/Makefile2:276: CMakeFiles/open_htj2k_enc.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

I'd like to know whether it is because something is wrong with my modification of the CmakeLists.txt, or the source code now does not support armv7-a.

**Comment by osamu620** [comment]
Hi @v2aus ,

I'm sorry for not getting back to you sooner.
This question in Stackoverflow seems to be relevant.
https://stackoverflow.com/questions/46999056/crosscompile-undefined-reference-to-std-atomic-futex-unsigned-base-m-futex

Maybe commenting out the 'find_package(Threads)' line in CMakeLists.txt is a possible workaround because the error message seems to be related to multi-threading.

**Comment by osamu620** [comment]
@v2aus 

If you are on a Debian-based distro, the following workaround should work:

- Remove `-mno-omit-leaf-frame-pointer` from `CMakeLists.txt`
 
- set `ENABLE_ARM_NEON` to `OFF` (as you mentioned)

- Prepare cross-compiling environment
```
sudo apt install g++-arm-linux-gnueabihf
sudo dpkg --add-architecture armhf
sudo apt update
sudo apt install libc6:armhf libstdc++6:armhf
```

- cmake with specifying the compiler
```
 cmake -B./build-32bit -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -G Ninja
```

For example, 

```
file build-32bit/bin/libopen_htj2k_R.so
```

returns

```
build-32bit/bin/libopen_htj2k_R.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=64c71389dd4b344e258df37e549ac8e4acbc5a2e, not stripped
```

and all the tests have been passed.
