### ISSUE TITLE
encoder: encode already-subsampled images

### ISSUE THREAD

**Issue by boxerab** [osamu620/OpenHTJ2K#20]
It would useful to support encoding of sub-sampled images.

**Comment by osamu620** [comment]
@boxerab 

Do you mean it is useful to support input files that are for Y, Cb (sub-sampled), and Cr (Sub-sampled) ?
or
the internal mechanism to convert RGB input into YCbCr chroma sub-sampled components?

**Comment by boxerab** [comment]
@osamu620 thanks for your reply. I was looking for the simplest way of supporting files at are already sub-sampled,
and this would be pgx, as the library already can read and write this format. Performing the sub-sampling is not necessary, I think.

**Comment by osamu620** [comment]
@boxerab I will figure out the way to accommodate multiple components with sub-sampling. It will take a while :)

**Comment by boxerab** [comment]
Fantastic! Thanks

**Comment by osamu620** [comment]
@boxerab 
There are a lot of inefficient parts in the code. I will improve them step-by-step in the near future.

**Comment by boxerab** [comment]
> @boxerab
> There are a lot of inefficient parts in the code. I will improve them step-by-step in the near future.

@osamu620 thanks, looking forward to your improvements.
