### ISSUE TITLE
Question about std::thread functions 

### ISSUE THREAD

**Issue by Jamaika1** [osamu620/OpenHTJ2K#27]
Is there any way to disable threadpool.hpp?
I know this is a stupid question. It's good that the codec has the newer C++17 language. With only gcc 12.0.0 it isn't possible to create codec under Windows. Unless author doesn't want amateur to compile with gcc.
Will not apply the mingwstdthread plugins to std::thread. 
Is there any way to disable threadpool.hpp?
https://github.com/meganz/mingw-std-threads
https://github.com/Jamaika1/mingw_std_threads

**Comment by osamu620** [comment]
@boxerab 
According to @Jamaika1 's question, how do you think? I think it makes some sense to have an option to disable threadpool.

**Comment by boxerab** [comment]
@osamu620 I think it is a good idea to allow user to set number of threads. If number of threads equals 1, then thread pool is disabled. However, the compiler will still need to compile the threading code. 

So, if @Jamaika1 wants to disable **compiling** of the threadpool, I think this should be done in a separate fork of the project.

**Comment by Jamaika1** [comment]
How do I set in help thread one?
