### ISSUE TITLE
Colours are incorrect when encoding with 0 wavelet decompositions

### ISSUE THREAD

**Issue by boxerab** [osamu620/OpenHTJ2K#50]
It looks like no colour transform is applied.

**Comment by osamu620** [comment]
Could you give us the information on the color space of input images?

**Comment by boxerab** [comment]
@osamu620 thanks, here is a sample image:

[boats.zip](https://github.com/osamu620/OpenHTJ2K/files/8054870/boats.zip)

**Comment by osamu620** [comment]
@boxerab Thanks. I compressed the attached .ppm file with the following command line:

```
./open_htj2k_enc -i boats.ppm -o boats.j2c Clevels=0
```
then I got 
[boats.j2c.zip](https://github.com/osamu620/OpenHTJ2K/files/8054875/boats.j2c.zip)

I think I could not reproduce the error. Could you give me the exact command line you have used?

**Comment by boxerab** [comment]
thanks, here are my command line args:

`Creversible=yes  Cblk="{32,32}" Clevels=0`

**Comment by osamu620** [comment]
@boxerab with the given command line, I could not reproduce the problem. Do you have more information (e.g. platform, compiler, etc)?

**Comment by boxerab** [comment]
@osamu620 you're right, sorry for the noise! closing.
