### ISSUE TITLE
Problem with decoding files

### ISSUE THREAD

**Issue by Jamaika1** [osamu620/OpenHTJ2K#89]
How to properly decode files ppm with htj2k?
https://github.com/osamu620/OpenHTJ2K/commit/d1cd229a76da78c21ac9f80c3310a19b32d3d412
htj2k-cjhc.exe -i image_21447_24bit.ppm -o image_21447_24bit-jhc.j2c Creversible=yes -num_threads 1
htj2k-djhc.exe -i image_21447_24bit-jhc.j2c -o image_21447_24bit-jhc_hc.ppm -num_threads 1
https://www.sendspace.com/file/ny7822

**Comment by osamu620** [comment]
I could not regenerate the problem. Please make sure that you use the latest main branch.
